# Generated by Django 3.2.3 on 2021-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videodisplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='imgs')),
                ('likes', models.IntegerField()),
                ('desc', models.TextField()),
                ('owner', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
