# Generated by Django 3.2.3 on 2021-05-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidshower', '0002_alter_videodisplayer_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodisplayer',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videodisplayer',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
