# Generated by Django 3.2.3 on 2021-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidshower', '0003_auto_20210526_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodisplayer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videodisplayer',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
