# Generated by Django 3.2.3 on 2021-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidshower', '0005_usermodellikedvideoslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodellikedvideoslist',
            name='likedvids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
